def a(turt):
    turt.setheading(0)
    turt.pu()
    turt.fd(10)
    turt.right(90)
    turt.fd(10)
    turt.pd()
    turt.fd(40)
    turt.right(180)
    turt.fd(40)
    turt.right(90)
    turt.fd(20)
    turt.right(90)
    turt.fd(40)
    turt.right(180)
    turt.fd(20)
    turt.left(90)
    turt.fd(20)
    turt.pu()
    # fixes
    turt.right(90)
    turt.fd(30)
    turt.right(90)
    turt.fd(30)
    # tur.right(180)


def b(turt):
    turt.pu()
    turt.fd(10)
    turt.right(90)
    turt.fd(10)
    turt.pd()
    turt.fd(40)
    turt.left(90)
    turt.fd(20)
    turt.left(90)
    turt.fd(20)
    turt.left(90)
    turt.fd(20)
    turt.right(180)
    turt.fd(20)
    turt.left(90)
    turt.fd(20)
    turt.left(90)
    turt.fd(20)
    turt.pu()
    turt.right(180)
    turt.fd(30)
    turt.left(90)
    turt.fd(10)
    turt.right(90)


def c(turt):
    turt.pu()
    turt.fd(10)
    turt.right(90)
    turt.fd(10)
    turt.pd()
    turt.left(90)
    turt.fd(20)
    turt.right(180)
    turt.fd(20)
    turt.left(90)
    turt.fd(40)
    turt.left(90)
    turt.fd(20)
    turt.pu()
    turt.fd(10)
    turt.left(90)
    turt.fd(50)
    turt.right(90)


def d(turt):
    turt.pu()
    turt.fd(10)
    turt.right(90)
    turt.fd(10)
    turt.pd()
    turt.fd(40)
    turt.left(112.5)
    turt.fd(30)
    turt.left(67.5)
    turt.fd(20)
    turt.left(71)
    turt.fd(30)
    turt.pu()
    turt.right(161)
    turt.fd(30)
    turt.left(90)
    turt.fd(10)
    turt.right(90)


def e(turt):
    turt.pu()
    turt.fd(10)
    turt.right(90)
    turt.fd(10)
    turt.pd()
    turt.fd(40)
    turt.left(90)
    turt.fd(20)
    turt.right(180)
    turt.fd(20)
    turt.right(90)
    turt.fd(20)
    turt.right(90)
    turt.fd(20)
    turt.right(180)
    turt.fd(20)
    turt.right(90)
    turt.fd(20)
    turt.right(90)
    turt.fd(20)
    turt.pu()
    turt.fd(10)
    turt.left(90)
    turt.fd(10)
    turt.right(90)


def f(tur):
    tur.pu()
    tur.fd(10)
    tur.right(90)
    tur.fd(10)
    tur.pd()
    tur.fd(40)
    tur.right(180)
    tur.fd(20)
    tur.right(90)
    tur.fd(20)
    tur.right(180)
    tur.fd(20)
    tur.right(90)
    tur.fd(20)
    tur.right(90)
    tur.fd(20)
    tur.pu()
    tur.fd(10)
    tur.left(90)
    tur.fd(10)
    tur.right(90)


def g(tur):
    tur.pd()
    tur.forward(30)
    tur.right(180)
    tur.forward(30)
    tur.left(90)
    tur.forward(60)
    tur.left(90)
    tur.forward(30)
    tur.left(90)
    tur.forward(20)
    tur.left(90)
    tur.forward(20)
    tur.right(180)
    tur.forward(20)
    tur.right(90)
    tur.forward(20)
    tur.right(90)
    tur.forward(30)
    tur.right(90)
    tur.forward(60)
    tur.right(90)
    tur.forward(30)
    tur.pu()
    tur.forward(5)
    tur.pd()


def h(tur):
    tur.pd()
    tur.right(90)
    tur.forward(60)
    tur.right(180)
    tur.forward(30)
    tur.right(90)
    tur.forward(30)
    tur.left(90)
    tur.forward(30)
    tur.right(180)
    tur.forward(60)
    tur.pu()
    tur.right(180)
    tur.forward(60)
    tur.right(90)
    tur.forward(10)
    tur.pd()


def i(tur):
    tur.pd()
    tur.forward(30)
    tur.right(180)
    tur.forward(15)
    tur.left(90)
    tur.forward(60)
    tur.left(90)
    tur.forward(15)
    tur.left(180)
    tur.forward(30)
    tur.left(180)
    tur.forward(15)
    tur.left(90)
    tur.forward(60)
    tur.right(90)
    tur.forward(15)
    tur.pu()
    tur.forward(5)
    tur.pd()


def j(tur):
    tur.pd()
    tur.forward(30)
    tur.right(180)
    tur.forward(10)
    tur.left(90)
    tur.forward(60)
    tur.right(90)
    tur.forward(20)
    tur.right(90)
    tur.forward(15)
    tur.pu()
    tur.forward(45)
    tur.right(90)
    tur.forward(40)
    tur.pd()


def k(tur):
    tur.pd()
    tur.right(90)
    tur.forward(60)
    tur.right(180)
    tur.forward(30)
    tur.right(45)
    tur.forward(40)
    tur.right(180)
    tur.forward(40)
    tur.left(90)
    tur.forward(40)
    tur.pu()
    tur.left(135)
    tur.forward(60)
    tur.right(90)
    tur.forward(5)
    tur.pd()


def l(tur):
    tur.setheading(0)
    tur.pd()
    tur.right(90)
    tur.fd(60)
    tur.left(90)
    tur.fd(40)
    tur.pu()
    tur.right(-90)
    tur.fd(60)
    tur.right(90)


def m(tur):
    tur.pu()
    tur.right(90)
    tur.fd(60)
    tur.left(90)
    tur.fd(10)
    tur.pd()
    tur.left(90)
    tur.fd(60)
    tur.right(130)
    tur.fd(30)
    tur.left(90)
    tur.fd(30)
    tur.right(140)
    tur.fd(60)
    tur.pu()
    tur.right(180)
    tur.fd(60)
    tur.right(90)
    tur.fd(10)


def n(tur):
    tur.pu()
    tur.right(90)
    tur.fd(60)
    tur.right(-90)
    tur.pd()
    tur.left(90)
    tur.fd(60)
    tur.right(130)
    tur.fd(70)
    tur.left(130)
    tur.fd(50)
    tur.pu()
    tur.right(90)
    tur.fd(10)


def o(tur):
    tur.pu()
    tur.fd(15)
    tur.right(90)
    tur.fd(30)
    tur.pd()
    tur.circle(35, 360)
    tur.pu()
    tur.fd(20)
    tur.right(-90)
    tur.fd(65)
    tur.right(90)
    tur.fd(15)
    tur.pu()
    tur.right(180)
    tur.fd(65)
    tur.right(90)
    tur.fd(10)


def p(tur):
    tur.pu()
    tur.right(90)
    tur.fd(20)
    tur.left(90)
    tur.pd()
    tur.circle(15, 180)
    tur.left(90)
    tur.fd(60)
    tur.pu()
    tur.right(-90)
    tur.fd(30)
    tur.right(-90)
    tur.fd(60)
    tur.right(90)


def q(tur):
    tur.setheading(0)
    tur.pu()
    tur.fd(5)
    tur.right(90)
    tur.fd(5)
    tur.pd()
    tur.fd(40)
    tur.left(90)
    tur.fd(30)
    tur.right(45)
    tur.fd(10)
    tur.bk(10)
    tur.right(-135)
    tur.fd(40)
    tur.right(270)
    tur.fd(30)
    tur.pu()
    tur.right(180)
    tur.fd(40)
    tur.pu()
    tur.right(0)


def r(tur):
    tur.setheading(0)
    tur.pu()
    tur.fd(5)
    tur.right(90)
    tur.fd(5)
    tur.pd()
    tur.fd(40)
    tur.bk(40)
    tur.left(90)
    tur.fd(30)
    tur.right(90)
    tur.fd(20)
    tur.right(90)
    tur.fd(20)
    tur.right(-135)
    tur.fd(30)
    tur.pu()
    tur.right(-135)
    tur.fd(50)
    tur.right(90)


def s(tur):
    tur.setheading(0)
    tur.pu()
    tur.fd(5)
    tur.pd()
    tur.fd(35)
    tur.bk(35)
    tur.right(90)
    tur.fd(25)
    tur.right(270)
    tur.fd(35)
    tur.right(90)
    tur.fd(25)
    tur.right(-270)
    tur.fd(35)
    tur.pu()
    tur.right(180)
    tur.fd(50)
    tur.right(-90)
    tur.fd(50)
    tur.right(90)


def t(tur):
    tur.setheading(0)
    tur.pu()
    tur.fd(5)
    tur.pd()
    tur.fd(35)
    tur.bk(17.5)
    tur.right(90)
    tur.fd(50)
    tur.pu()
    tur.right(-90)
    tur.fd(20)
    tur.right(-90)
    tur.fd(55)
    tur.right(90)


def u(tur):
    tur.pd()
    tur.right(90)
    tur.fd(80)
    tur.right(-45)
    tur.fd(20)
    tur.right(-45)
    tur.fd(40)
    tur.right(-45)
    tur.fd(20)
    tur.right(-45)
    tur.fd(80)
    tur.pu()
    tur.right(90)
    tur.fd(7)


def v(tur):
    tur.setheading(0)
    tur.pu()
    tur.fd(5)
    tur.right(45)
    tur.fd(5)
    tur.pd()
    tur.fd(60)
    tur.right(270)
    tur.fd(60)
    tur.pu()
    tur.right(50)
    tur.fd(10)


def w(tur):
    tur.pd()
    tur.right(90)
    tur.fd(55)
    tur.right(-140)
    tur.fd(40)
    tur.right(90)
    tur.fd(40)
    tur.right(-140)
    tur.fd(55)
    tur.pu()
    tur.right(90)
    tur.fd(7)


def x(tur):
    tur.pd()
    tur.right(45)
    tur.fd(60)
    tur.right(-180)
    tur.fd(30)
    tur.right(90)
    tur.fd(30)
    tur.right(180)
    tur.fd(60)
    tur.pu()
    tur.right(180)
    tur.fd(60)
    tur.right(45)
    tur.fd(10)


def y(tur):
    tur.pd()
    tur.right(45)
    tur.fd(30)
    tur.right(-90)
    tur.fd(30)
    tur.right(-180)
    tur.fd(30)
    tur.right(-45)
    tur.fd(40)
    tur.pu()
    tur.left(90)
    tur.forward(20)
    tur.left(90)
    tur.forward(50)
    tur.right(90)
    tur.fd(10)


def z(tur):
    tur.pd()
    tur.forward(30)
    tur.left(245)
    tur.forward(70)
    tur.left(115)
    tur.forward(30)
