from functools import reduce

from lab5.models.Identifiable import Identifiable


class Order(Identifiable):
    def __init__(self, id_=None, customer_id: int = None, item_ids=None, total_price: int = None, dict_=None):
        super().__init__(id_)
        self.__customer_id = customer_id
        self.__item_ids = item_ids
        self.__total_price = total_price
        if dict_ is not None:
            self.__dict__ = dict_

    def __eq__(self, other):
        return super().__eq__(
            other) and self.__customer_id == other.__customer_id and self.__item_ids == other.__item_ids

    def __str__(self):
        return super().__str__() + f", Kunden-ID = '{self.__customer_id}', Artikel = '{self.__item_ids}', Gesamtkosten = '{self.__total_price}'"

    def __hash__(self):
        return hash(self.__str__())

    @property
    def customer_id(self):
        return self.__customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        self.__customer_id = customer_id

    @property
    def item_ids(self):
        return self.__item_ids

    @item_ids.setter
    def item_ids(self, item_ids):
        self.__item_ids = item_ids

    @property
    def total_price(self):
        return self.__total_price

    @total_price.setter
    def total_price(self, total_price):
        self.__total_price = total_price

    def compute_total_price(self, items):
        """
        Adds up the prices from the items list
        :returns: Total order price
        """
        # items[0] = items[0].id
        self.__total_price = reduce(lambda a, m: a + m.price, items, 0)
        return self.__total_price

    def __generate_bill(self, items):
        """
        Generates and returns a bill, containing the items of this order
        :returns: The bill as a string
        """
        self.compute_total_price(items)
        bill_lines = list(map(lambda item: f"{item.name} " + "." * (30 - len(item.name)) + f" {item.price}", items))
        bill_lines.append(f"\nGesamtkosten " + '.' * 18 + f" {self.__total_price}")

        return reduce(lambda a, b: a + '\n' + b, bill_lines)

    def print_bill(self, items):
        """
        Prints the bill of this order generated by the __generate_bill method
        """
        print(self.__generate_bill(items))

    def pprint(self, customer, items):
        """
        Returns a string for pretty printing an order
        :param customer: The customer on this order
        :param items: A list of items contained in this order
        """
        return f"Bestellung {self.id} für {customer.name} - Adresse: {customer.address}:\n" + self.__generate_bill(
            items)
